import React, { useState, useEffect } from 'react';
import { Typography, Box, Paper } from "@mui/material"
import { Tooltip } from 'react-tooltip'
import 'react-tooltip/dist/react-tooltip.css'

const StoryMeaning = ({text}:{text:string}) => {
  const wordMeaning:Map<string,string> = new Map([
    ['Sherlock', 'Sherlock'],
    ['Holmes', 'Holmes'],
    ['finds', 'trouve'],
    ['himself', 'lui-même'],
    ['in', 'dans'],
    ['a', 'un'],
    ['quaint', 'pittoresque'],
    ['Parisian', 'parisien'],
    ['café', 'café'],
    ['sipping', 'sirotant'],
    ['espresso', 'espresso'],
    ['while', 'pendant'],
    ['reading', 'lisant'],
    ['cryptic', 'cryptique'],
    ['letter', 'lettre'],
    ['The', 'La'],
    ['note', 'note'],
    ['written', 'écrite'],
    ['elegant', 'élégant'],
    ['French', 'français'],
    ['warns', 'avertit'],
    ['of', 'de'],
    ['shadow', 'ombre'],
    ['that', 'qui'],
    ['devours', 'dévore'],
    ['city', 'ville'],
    ['light', 'lumière'],
    ['Intrigued', 'Intrigué'],
    ['notices', 'remarque'],
    ['faint', 'légère'],
    ['scent', 'odeur'],
    ['lavender', 'lavande'],
    ['and', 'et'],
    ['smudge', 'tache'],
    ['ink', 'encre'],
    ['clues', 'indices'],
    ['pointing', 'pointant'],
    ['to', 'vers'],
    ['sender', 'expéditeur'],
    ['ends', 'se termine'],
    ['with', 'avec'],
    ['plea', 'supplication'],
    ['Meet', 'Rencontrez'],
    ['me', 'moi'],
    ['at', 'à'],
    ['Eiffel Tower', 'Tour Eiffel'],
    ['midnight', 'minuit'],
    ['Time', 'Le temps'],
    ['is', 'est'],
    ['running', 'en train de'],
    ['out', 's\'écouler'],
    ['Investigate', 'Enquêter'],
    ['the', 'la'],
    ['nearby', 'proche'],
    ['perfume', 'parfum'],
    ['shop', 'boutique'],
    ['Head', 'Aller'],
    ['straight', 'directement'],
    ['follows', 'suit'],
    ['small', 'petite'],
    ['tucked', 'nichée'],
    ['alley', 'ruelle'],
    ['shopkeeper', 'commerçante'],
    ['nervous', 'nerveuse'],
    ['woman', 'femme'],
    ['reveals', 'révèle'],
    ['rare', 'rare'],
    ['oil', 'huile'],
    ['sold', 'vendue'],
    ['only', 'seulement'],
    ['aristocrats', 'aristocrates'],
    ['She', 'Elle'],
    ['mentions', 'mentionne'],
    ['wealthy', 'riche'],
    ['client', 'client'],
    ['recently', 'récemment'],
    ['purchased', 'achetée'],
    ['Baroness', 'Baronne'],
    ['ties', 'liens'],
    ['hidden', 'caché'],
    ['compartment', 'compartiment'],
    ['behind', 'derrière'],
    ['counter', 'comptoir'],
    ['grows', 'devient'],
    ['uneasy', 'mal à l\'aise'],
    ['Press', 'Presser'],
    ['for', 'pour'],
    ['more', 'plus'],
    ['information', 'informations'],
    ['about', 'à propos'],
    ['Investigate', 'Enquêter'],
    ['At', 'À'],
    ['waits', 'attend'],
    ['under', 'sous'],
    ['moonlight', 'clair de lune'],
    ['cloaked', 'encapuchonné'],
    ['figure', 'figure'],
    ['approaches', 'approche'],
    ['but', 'mais'],
    ['flees', 'fuit'],
    ['when', 'quand'],
    ['calls', 'appelle'],
    ['out', 'dehors'],
    ['Chasing', 'Poursuivant'],
    ['dropped', 'tombé'],
    ['handkerchief', 'mouchoir'],
    ['initials', 'initiales'],
    ['B.D.', 'B.D.'],
    ['trace', 'trace'],
    ['gunpowder', 'poudre à canon'],
    ['suspicious', 'suspect'],
    ['man', 'homme'],
    ['trench', 'tranchée'],
    ['coat', 'manteau'],
    ['watches', 'regarde'],
    ['from', 'depuis'],
    ['shadows', 'ombres'],
    ['clutching', 'serrant'],
    ['briefcase', 'mallette'],
    ['Follow', 'Suivre'],
    ['into', 'dans'],
    ['dark', 'sombre'],
    ['alleys', 'ruelles'],
    ['Confront', 'Confronter'],
    ['opens', 'ouvre'],
    ['ledger', 'registre'],
    ['detailing', 'détail'],
    ['illegal', 'illégal'],
    ['shipments', 'expéditions'],
    ['Midnight', 'Minuit'],
    ['Exchange', 'Échange'],
    ['Suddenly', 'Soudainement'],
    ['pulls', 'tire'],
    ['knife', 'couteau'],
    ['demanding', 'exigeant'],
    ['leave', 'partir'],
    ['disarms', 'désarme'],
    ['realizes', 'réalise'],
    ['network', 'réseau'],
    ['extensive', 'étendu'],
    ['than', 'que'],
    ['thought', 'pensé'],
    ['pursues', 'poursuit'],
    ['winding', 'sinueux'],
    ['corners', 'coins'],
    ['young', 'jeune'],
    ['turns', 'se révèle'],
    ['expose', 'exposer'],
    ['mother’s', 'mère'],
    ['crimes', 'crimes'],
    ['hands', 'donne'],
    ['key', 'clé'],
    ['secret', 'secret'],
    ['vault', 'coffre'],
    ['beneath', 'sous'],
    ['stored', 'stocké'],
    ['Trust', 'Faire confiance'],
    ['investigate', 'enquêter'],
    ['Demand', 'Exiger'],
    ['come', 'venir'],
    ['police', 'police'],
    ['confronts', 'confronte'],
    ['opens', 'ouvre'],
    ['stolen', 'volé'],
    ['artifacts', 'artefacts'],
    ['claims', 'prétend'],
    ['working', 'travaillant'],
    ['plans', 'prévoit'],
    ['sell', 'vendre'],
    ['offers', 'propose'],
    ['cut', 'part'],
    ['profits', 'bénéfices'],
    ['stay', 'rester'],
    ['silent', 'silencieux'],
    ['strange', 'étrange'],
    ['symbol', 'symbole'],
    ['linked', 'lié'],
    ['society', 'société'],
    ['Pretend', 'Faire semblant'],
    ['accept', 'accepter'],
    ['deal', 'accord'],
    ['gather', 'recueillir'],
    ['Arrest', 'Arrêter'],
    ['seize', 'saisir'],
    ['sneaks', 'se faufile'],
    ['avoiding', 'évitant'],
    ['guards', 'gardes'],
    ['overhears', 'entend'],
    ['discussing', 'discutant'],
    ['weapon', 'arme'],
    ['mass', 'masse'],
    ['destruction', 'destruction'],
    ['must', 'doit'],
    ['act', 'agir'],
    ['quickly', 'rapidement'],
    ['prevent', 'empêcher'],
    ['use', 'utilisation'],
    ['Sabotage', 'Saboter'],
    ['before', 'avant'],
    ['moved', 'déplacé'],
    ['Escape', 'S\'échapper'],
    ['alert', 'alerter'],
    ['authorities', 'autorités'],
    ['returns', 'retourne'],
    ['gathering', 'recueillant'],
    ['evidence', 'preuves'],
    ['learns', 'apprend'],
    ['cover', 'couverture'],
    ['smuggling', 'contrebande'],
    ['rushes', 'se précipite'],
    ['already', 'déjà'],
    ['there', 'là'],
    ['preparing', 'préparant'],
    ['shipment', 'expédition'],
    ['Confront', 'Confronter'],
    ['directly', 'directement'],
    ['Set', 'Mettre'],
    ['trap', 'piège'],
    ['intercept', 'intercepter'],
    ['arrives', 'arrive'],
    ['overseeing', 'supervisant'],
    ['confronts', 'confronte'],
    ['reveals', 'révèle'],
    ['armed', 'armé'],
    ['decide', 'décider'],
    ['whether', 'si'],
    ['disarm', 'désarmer'],
    ['evacuate', 'évacuer'],
    ['reports', 'rapporte'],
    ['findings', 'découvertes'],
    ['hesitant', 'hésitant'],
    ['proof', 'preuve'],
    ['stop', 'arrêter'],
    ['himself', 'lui-même'],
    ['returns', 'retourne'],
    ['underway', 'en cours'],
    ['Infiltrate', 'Infiltre'],
    ['alone', 'seul'],
    ['Convince', 'Convaincre'],
    ['raid', 'raid'],
    ['location', 'lieu'],
    ['unlocks', 'déverrouille'],
    ['finding', 'trouvant'],
    ['helps', 'aide'],
    ['disarm', 'désarmer'],
    ['arrives', 'arrive'],
    ['armed', 'armé'],
    ['guards', 'gardes'],
    ['think', 'penser'],
    ['fast', 'vite'],
    ['Use', 'Utiliser'],
    ['mechanisms', 'mécanismes'],
    ['against', 'contre'],
    ['Surrender', 'Se rendre'],
    ['buy', 'acheter'],
    ['time', 'temps'],
    ['escape', 'échapper'],
    ['takes', 'prend'],
    ['dismiss', 'rejeter'],
    ['claims', 'revendications'],
    ['infiltrated', 'infiltré'],
    ['force', 'force'],
    ['public', 'public'],
    ['expose', 'exposer'],
    ['pretends', 'fait semblant'],
    ['gains', 'gagne'],
    ['access', 'accès'],
    ['inner', 'intérieur'],
    ['circle', 'cercle'],
    ['hidden', 'caché'],
    ['decide', 'décider'],
    ['proceed', 'procéder'],
    ['within', 'à l\'intérieur'],
    ['operation', 'opération'],
    ['arrests', 'arrête'],
    ['intact', 'intact'],
    ['Track', 'Pister'],
    ['down', 'en bas'],
    ['hideout', 'cachette'],
    ['bait', 'appât'],
    ['lure', 'leurrer'],
    ['successfully', 'avec succès'],
    ['disarms', 'désarme'],
    ['using', 'utilisant'],
    ['keen', 'aiguisé'],
    ['intellect', 'intellect'],
    ['reverse', 'inverser'],
    ['captured', 'capturé'],
    ['celebrates', 'célèbre'],
    ['vigilant', 'vigilant'],
    ['knowing', 'sachant'],
    ['never', 'jamais'],
    ['truly', 'vraiment'],
    ['disappears', 'disparaît'],
    ['fails', 'échoue'],
    ['manage', 'gérer'],
    ['evacuate', 'évacuer'],
    ['minimizing', 'minimisant'],
    ['casualties', 'victimes'],
    ['escapes', 's\'échappe'],
    ['grapple', 'lutter'],
    ['lives', 'vies'],
    ['lost', 'perdu'],
    ['weight', 'poids'],
    ['choices', 'choix'],
    ['desperate', 'désespéré'],
    ['bid', 'tentative'],
    ['triggers', 'déclenche'],
    ['self-destruct', 'autodestruction'],
    ['sequence', 'séquence'],
    ['knowing', 'sachant'],
    ['cost', 'coût'],
    ['life', 'vie'],
    ['explosion', 'explosion'],
    ['contained', 'contenue'],
    ['saving', 'sauver'],
    ['posthumously', 'à titre posthume'],
    ['honored', 'honoré'],
    ['Watson', 'Watson'],
    ['receiving', 'recevant'],
    ['final', 'final'],
    ['expressing', 'exprimant'],
    ['resolve', 'résolution'],
    ['captures', 'capture'],
    ['chaos', 'chaos'],
    ['Vowing', 'Jurant'],
    ['revenge', 'vengeance'],
    ['disappears', 'disparaît'],
    ['edge', 'bord'],
    ['preparing', 'préparant'],
    ['next', 'prochain'],
    ['move', 'mouvement'],
    ['exposes', 'expose'],
    ['fails', 'échoue'],
    ['leading', 'menant'],
    ['partial', 'partiel'],
    ['destruction', 'destruction'],
    ['arrested', 'arrêté'],
    ['damage', 'dommage'],
    ['serves', 'sert'],
    ['grim', 'sombre'],
    ['reminder', 'rappel'],
    ['justice', 'justice'],
    ['captured', 'capturé'],
    ['activated', 'activé'],
    ['devastating', 'dévastant'],
    ['left', 'laissé'],
    ['ruins', 'ruines'],
    ['failure', 'échec'],
    ['haunts', 'hante'],
    ['languishes', 'languit'],
    ['captivity', 'captivité'],
    ['uses', 'utilise'],
    ['rallying', 'ralliant'],
    ['against', 'contre'],
    ['destroyed', 'détruit'],
    ['process', 'processus'],
    ['celebrated', 'célébré'],
    ['dismantled', 'démantelé'],
    ['stops', 'arrête'],
    ['quietly', 'silencieusement'],
    ['preventing', 'empêchant'],
    ['panic', 'panique'],
    ['safe', 'sûr'],
    ['fight', 'combat'],
    ['far', 'loin'],
    ['over', 'fini'],
    ['betrayed', 'trahi'],
    ['plans', 'plans'],
    ['activated', 'activé'],
    ['face', 'face'],
    ['consequences', 'conséquences'],
    ['uncovers', 'découvre'],
    ['ambushed', 'embusqué'],
    ['killed', 'tué'],
    ['truth', 'vérité'],
    ['dies', 'meurt'],
    ['fate', 'destin'],
    ['remains', 'reste'],
    ['mystery', 'mystère'],
    ['convinces', 'convainc'],
    ['resulting', 'résultant'],
    ['devastates', 'dévaste'],
    ['mourn', 'pleurer'],
    ['captures', 'capture'],
    ['lost', 'perdu'],
    ['process', 'processus'],
    ['threat', 'menace'],
    ['lingers', 'persiste'],
    ['helps', 'aide'],
    ['redeeming', 'rachetant'],
    ['valuable', 'précieux'],
    ['ally', 'allié'],
    ['fight', 'combat'],
    ['uses', 'utilise'],
    ['remotely', 'à distance'],
    ['destroys', 'détruit'],
    ['part', 'partie'],
    ['rebuild', 'reconstruire'],
    ['confronts', 'confronte'],
    ['already', 'déjà'],
    ['route', 'route'],
    ['peril', 'péril'],
    ['leaves', 'laisse'],
    ['detailing', 'détail'],
    ['regrets', 'regrets'],
    ['testament', 'testament'],
    ['dedication', 'dédication'],
    ['face', 'face'],
    ['defeat', 'défaite']
]);

  const Word=({id, word}:{id:string, word:string})=>{
    if(!wordMeaning.has(word)){
        return (<Box
            sx={{
                display:'inline-block'
            }}>
                <span>{word}&nbsp;</span>
        </Box>);
    }
    return(<Box
        sx={{
            display:'inline-block'
        }}>
        <a
            data-tooltip-id={id}
            data-tooltip-content={wordMeaning.get(word)}
            data-tooltip-place="top">
            {word}&nbsp;
        </a>
        <Tooltip id={id}  
        opacity={1} 
        style={{
            color: "red",
            background: "white",
            
        }}/>
    </Box>);
  };

  const words = text.split(' ').map(
    (word,index)=>{
        return (<Word 
            key={"word-"+index}
            id={"word-"+index}
            word={word}
        />)
    }
  )


  return <>{words}</>;
};

export default StoryMeaning;